### ISSUE TITLE
match.php Just Show Me 

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#104] opened 2017-12-03 14:59 UTC
@Discordanian 
Change the name of the "Just Show Me" button to "Show Organizations"
When displaying organizations, change the name of the button to "Hide Organizations"

**Comment by Discordanian** [comment] 2017-12-04 17:51
Duplicate of Issue 91.

**Comment by Discordanian** [comment] 2018-01-19 00:02
[master c083357] Issue #104
 1 files changed, 4 insertions(+), 0 deletions(-)
Counting objects: 7, done.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 457 bytes, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To git@github.com:Discordanian/mmatch.git
   5bc96a2..c083357  master -> master

**Closed by Discordanian** 2018-01-19 00:02 UTC
